spring:
  profiles:
    active: local     # 本地开发环境
#    active: dev       # 开发环境
#    active: test      # Docker 环境里的纯测试环境
#    active: pre       # 预发环境
#    active: online    # 生产环境



logging:
  config: classpath:logback.xml
  path: /Users/RuzzZZ/logs/spring-boot-demo/demo.log
  level: info
